language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

install: true

script: cargo build --verbose

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true

cache: cargo

before_deploy:
  - cargo build --release --verbose
  - cp "target/release/dots" "dots-$TRAVIS_TAG-$TRAVIS_OS_NAME-x86_64"

deploy:
  provider: releases
  api_key:
    secure: MhAE5zIimbfGYnIrIgiB+yYLCd8LxmhosKGiipG2nPU8SqlL1/ngp4JEvmx37C/uI/aogqtJQCGna0H3ineHV56E9GwM2+d2q2G1EKQdFEWrgXsDjs9SkbJpe5wZ5C7MmY4olB+n+L+8G2f+7ASGSjt3ORE15c43fSi0/igI/+xrjP2lDrKOLZdAvi3p9FcAJ+Cv3sKnpejWE8XaEH+xPwfq1ICevm68K4hCA2rfm4KpsCIE44USS+78sVkmLE+ASVfoHLCNl0Y09z5P/IG3uCHfIchYN9QHs0psBUFt52TfXJP8iiip+Ww+7SPOeLMNalewiFWYs5XFfh4/rJhpWaO+1lVB5r7DidOINUBZIV3SZjoyTWCcjg3Vxwgq55g+ZTDnPjb+Gp3DWv/LnsCnqNnygPTlam4i07v2jYc9EE59ypqEdxNGjm/xf/ZQ72QK2QL+Br+IWE0AWybalALE7qZ6IhMnGGewkwDLvw8vTdLp9AdztbeEYdg/WluZ6KcHMs/nhv+CJEP3Bzqf6/xe1+V/zkZ398eVA7UViRQvfMNU1KOQqaB0qhNbX2bf0/88BO0xMarw/q+YdSX+Yum+RNsxdC/Zr/G289svu4KsTjtMC/zpp8Cr4xX3kL6JnNBf49KOh/KkHwKZLa+aPEVoBiliwdQQPTNwJ5LblVgmJw0=
  file: "dots-$TRAVIS_TAG-$TRAVIS_OS_NAME-x86_64"
  skip_cleanup: true
  on:
    rust: stable
    tags: true
